@startuml

title __UTIL's Class Diagram__\n

  namespace it.unive.dais.legodroid {
    namespace lib {
      namespace util {
        interface it.unive.dais.legodroid.lib.util.Consumer {
            {abstract} + call()
        }
      }
    }
  }
  

  namespace it.unive.dais.legodroid {
    namespace lib {
      namespace util {
        interface it.unive.dais.legodroid.lib.util.Function {
            {abstract} + apply()
            {static} + identity()
        }
      }
    }
  }
  

  namespace it.unive.dais.legodroid {
    namespace lib {
      namespace util {
        class it.unive.dais.legodroid.lib.util.Prelude {
            {static} + TAG : String
            {static} + hexArray : char[]
            {static} - TAG_BASE : String
            {static} + ReTAG()
            {static} + ReTAG()
            {static} + bytesToHex()
            {static} + concat()
            {static} + trap()
            {static} + trap()
        }
      }
    }
  }
  

  namespace it.unive.dais.legodroid {
    namespace lib {
      namespace util {
        interface it.unive.dais.legodroid.lib.util.ThrowingConsumer {
            + call()
            {abstract} + callThrows()
        }
      }
    }
  }
  

  namespace it.unive.dais.legodroid {
    namespace lib {
      namespace util {
        interface it.unive.dais.legodroid.lib.util.ThrowingRunnable {
            + run()
            {abstract} + runThrows()
        }
      }
    }
  }
  

  namespace it.unive.dais.legodroid {
    namespace lib {
      namespace util {
        class it.unive.dais.legodroid.lib.util.UnexpectedException {
            + UnexpectedException()
            + UnexpectedException()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
